#!/usr/bin/env stack runhaskell
{-# LANGUAGE OverloadedStrings #-}
{-# LANGUAGE TemplateHaskell   #-}
module Main where

import           Control.Monad    (forM_)
import           Data.Monoid      ((<>))
import           Data.Text        (Text, intercalate, pack)
import           Data.Text.IO     (putStrLn)
import           Internal.Helpers (getISOTime)
import           Internal.Partial (getPartials, partialName')
import           Partials
import           Prelude          hiding (intercalate, putStrLn)

-- This executable generates the src/Partials.hs file. The exe should be run
-- in the src directory.

partialNames :: [Text]
partialNames = map (\p->"Partials." <> partialName' p) $(getPartials)

main :: IO ()
main = do
    timeStr <- getISOTime
    putStrLn $ "-- Automatically generated by mkPartialsHs on " <> (pack timeStr)
    putStrLn "module Partials ("
    putStrLn $ intercalate "\n" (map ("    module "<>) partialNames)
    putStrLn ") where"
    putStrLn ""
    putStrLn $ intercalate "\n" (map ("import "<>) partialNames)
